INTERVIEW_MODES = ("COACH", "SIMULATION")

INTERVIEW_LEVELS = ("INTERN", "NEW_GRAD", "EARLY_CAREER")

INTERVIEW_STAGES = (
    "SETUP",
    "INTRODUCTION",
    "PROBLEM_UNDERSTANDING",
    "APPROACH_DISCOVERY",
    "APPROACH_DEFENSE",
    "IMPLEMENTATION",
    "TESTING_DEBUGGING",
    "COMPLEXITY_EDGE_CASES",
    "CONSTRAINT_MUTATION",
    "FINAL_DEFENSE",
    "WRAP_UP",
    "COMPLETED",
)

INTERVIEW_SESSION_STATUSES = (
    "READY",
    "ACTIVE",
    "RECONNECTING",
    "COMPLETED",
    "ABANDONED",
    "DELETION_PENDING",
)

EVENT_SOURCES = (
    "CANDIDATE_VOICE",
    "COUNTERQ_VOICE",
    "NATIVE_EDITOR",
    "NATIVE_RUNNER",
    "BROWSER_EXTENSION",
    "INTERVIEW_ORCHESTRATOR",
    "SYSTEM",
)

EVENT_TYPES = (
    "TRANSCRIPT_FINALIZED",
    "COUNTERQ_UTTERANCE_DELIVERED",
    "CODE_SNAPSHOT_CREATED",
    "MEANINGFUL_CODE_CHANGE",
    "RUN_CLICKED",
    "COMPILE_COMPLETED",
    "TEST_COMPLETED",
    "STAGE_CHANGED",
    "CANDIDATE_DECLARED_DONE",
    "CANDIDATE_INTERRUPTED_COUNTERQ",
    "COUNTERQ_INTERRUPTED_CANDIDATE",
    "REALTIME_DISCONNECTED",
    "REALTIME_RECONNECTED",
)

TRANSCRIPT_SPEAKERS = ("CANDIDATE", "COUNTERQ")

DELIVERY_STATES = (
    "STARTED",
    "DELIVERED",
    "PARTIALLY_DELIVERED",
    "INTERRUPTED",
    "CANCELLED",
)

CLAIM_ORIGIN_KINDS = (
    "TRANSCRIPT",
    "CODE",
    "EXECUTION",
    "MULTIMODAL_CONTEXT",
)

CLAIM_TYPES = (
    "ALGORITHM_CHOICE",
    "COMPLEXITY",
    "CORRECTNESS",
    "INVARIANT",
    "DATA_STRUCTURE",
    "ASSUMPTION",
    "EDGE_CASE",
    "IMPLEMENTATION",
    "TRADE_OFF",
)

CLAIM_STATUSES = (
    "PROPOSED",
    "ACCEPTED_AS_INTERPRETATION",
    "REJECTED",
    "SUPERSEDED",
)

EXAMINER_ACTIONS = ("WAIT", "OBSERVE", "ASK", "PROBE")

EXAMINER_DECISION_STATUSES = (
    "PROPOSED",
    "AUTHORIZED",
    "REJECTED",
    "STALE",
    "EXPIRED",
    "SUPERSEDED",
)

POLICY_GATE_OUTCOMES = (
    "AUTHORIZED",
    "REJECTED",
    "STALE",
    "BUDGET_DENIED",
    "STAGE_INVALID",
    "LOW_CONFIDENCE",
    "SUPERSEDED",
    "EXPIRED",
)

PROBE_STRATEGIES = (
    "WHY",
    "PROVE",
    "ASSUMPTION_CHALLENGE",
    "COUNTEREXAMPLE",
    "COMPLEXITY",
    "EDGE_CASE",
    "TRADE_OFF",
    "ALTERNATIVE",
    "IMPLEMENTATION_CHOICE",
    "CONSTRAINT_MUTATION",
    "FAILURE_MODE",
    "TRANSFER",
)

PROMPT_ORIGINS = ("STATE_MACHINE", "EXAMINER_DECISION", "SYSTEM")

PROMPT_KINDS = (
    "BASE_QUESTION",
    "CLARIFICATION",
    "PROBE",
    "TRANSITION",
    "INSTRUCTION",
    "TIME_WARNING",
)

PROMPT_STATUSES = (
    "PROPOSED",
    "AUTHORIZED",
    "DELIVERED",
    "ANSWERED",
    "REJECTED",
    "STALE",
    "EXPIRED",
    "INTERRUPTED",
    "CANCELLED",
)

RESPONSE_COMPLETION_REASONS = (
    "COMPLETE",
    "INTERRUPTED",
    "SUPERSEDED",
    "TIMEOUT",
    "SPONTANEOUS",
)

RESPONSE_SOURCE_ROLES = (
    "PRIMARY",
    "SUPPORTING",
    "CODE_CONTEXT",
    "RUN_CONTEXT",
)

AI_INVOCATION_STATUSES = (
    "STARTED",
    "SUCCEEDED",
    "FAILED",
    "CANCELLED",
    "TIMED_OUT",
)

CONVERSATION_FLOOR_STATES = (
    "CANDIDATE_SPEAKING",
    "CANDIDATE_THINKING",
    "COUNTERQ_SPEAKING",
    "IDLE",
    "INTERRUPTED",
)

EXECUTION_RUN_STATUSES = (
    "RUNNING",
    "SUCCEEDED",
    "COMPILE_ERROR",
    "RUNTIME_ERROR",
    "TIMED_OUT",
    "OUTPUT_LIMIT_EXCEEDED",
    "PROVIDER_ERROR",
)

TEST_RESULT_STATUSES = ("PASSED", "FAILED", "NOT_RUN")
