INTERVIEW_MODES = ("COACH", "SIMULATION")

INTERVIEW_LEVELS = ("INTERN", "NEW_GRAD", "EARLY_CAREER")

INTERVIEW_STAGES = (
    "SETUP",
    "INTRODUCTION",
    "PROBLEM_UNDERSTANDING",
    "APPROACH_DISCOVERY",
    "APPROACH_DEFENSE",
    "IMPLEMENTATION",
    "TESTING_DEBUGGING",
    "COMPLEXITY_EDGE_CASES",
    "CONSTRAINT_MUTATION",
    "FINAL_DEFENSE",
    "WRAP_UP",
    "COMPLETED",
)

INTERVIEW_SESSION_STATUSES = (
    "READY",
    "ACTIVE",
    "RECONNECTING",
    "COMPLETED",
    "ABANDONED",
    "DELETION_PENDING",
)

EVENT_SOURCES = (
    "CANDIDATE_VOICE",
    "COUNTERQ_VOICE",
    "NATIVE_EDITOR",
    "NATIVE_RUNNER",
    "BROWSER_EXTENSION",
    "INTERVIEW_ORCHESTRATOR",
    "SYSTEM",
)

EVENT_TYPES = (
    "TRANSCRIPT_FINALIZED",
    "COUNTERQ_UTTERANCE_DELIVERED",
    "CODE_SNAPSHOT_CREATED",
    "MEANINGFUL_CODE_CHANGE",
    "RUN_CLICKED",
    "COMPILE_COMPLETED",
    "TEST_COMPLETED",
    "STAGE_CHANGED",
    "CANDIDATE_DECLARED_DONE",
    "CANDIDATE_INTERRUPTED_COUNTERQ",
    "COUNTERQ_INTERRUPTED_CANDIDATE",
    "REALTIME_DISCONNECTED",
    "REALTIME_RECONNECTED",
)

TRANSCRIPT_SPEAKERS = ("CANDIDATE", "COUNTERQ")

DELIVERY_STATES = (
    "STARTED",
    "DELIVERED",
    "PARTIALLY_DELIVERED",
    "INTERRUPTED",
    "CANCELLED",
)
