INTERVIEW_MODES = ("COACH", "SIMULATION")

INTERVIEW_LEVELS = ("INTERN", "NEW_GRAD", "EARLY_CAREER")

INTERVIEW_STAGES = (
    "SETUP",
    "INTRODUCTION",
    "PROBLEM_UNDERSTANDING",
    "APPROACH_DISCOVERY",
    "APPROACH_DEFENSE",
    "IMPLEMENTATION",
    "TESTING_DEBUGGING",
    "COMPLEXITY_EDGE_CASES",
    "CONSTRAINT_MUTATION",
    "FINAL_DEFENSE",
    "WRAP_UP",
    "COMPLETED",
)

INTERVIEW_SESSION_STATUSES = (
    "READY",
    "ACTIVE",
    "RECONNECTING",
    "COMPLETED",
    "ABANDONED",
    "DELETION_PENDING",
)

EVENT_SOURCES = (
    "CANDIDATE_VOICE",
    "COUNTERQ_VOICE",
    "NATIVE_EDITOR",
    "NATIVE_RUNNER",
    "BROWSER_EXTENSION",
    "INTERVIEW_ORCHESTRATOR",
    "SYSTEM",
)

EVENT_TYPES = (
    "TRANSCRIPT_FINALIZED",
    "COUNTERQ_UTTERANCE_DELIVERED",
    "CODE_SNAPSHOT_CREATED",
    "MEANINGFUL_CODE_CHANGE",
    "RUN_CLICKED",
    "COMPILE_COMPLETED",
    "TEST_COMPLETED",
    "STAGE_CHANGED",
    "CANDIDATE_DECLARED_DONE",
    "CANDIDATE_INTERRUPTED_COUNTERQ",
    "COUNTERQ_INTERRUPTED_CANDIDATE",
    "REALTIME_DISCONNECTED",
    "REALTIME_RECONNECTED",
    "CANDIDATE_ASSISTANCE_REQUESTED",
)

TRANSCRIPT_SPEAKERS = ("CANDIDATE", "COUNTERQ")

DELIVERY_STATES = (
    "STARTED",
    "DELIVERED",
    "PARTIALLY_DELIVERED",
    "INTERRUPTED",
    "CANCELLED",
)

CLAIM_ORIGIN_KINDS = (
    "TRANSCRIPT",
    "CODE",
    "EXECUTION",
    "MULTIMODAL_CONTEXT",
)

CLAIM_TYPES = (
    "ALGORITHM_CHOICE",
    "COMPLEXITY",
    "CORRECTNESS",
    "INVARIANT",
    "DATA_STRUCTURE",
    "ASSUMPTION",
    "EDGE_CASE",
    "IMPLEMENTATION",
    "TRADE_OFF",
)

CLAIM_STATUSES = (
    "PROPOSED",
    "ACCEPTED_AS_INTERPRETATION",
    "REJECTED",
    "SUPERSEDED",
)

EXAMINER_ACTIONS = ("WAIT", "OBSERVE", "ASK", "PROBE")

EXAMINER_DECISION_STATUSES = (
    "PROPOSED",
    "AUTHORIZED",
    "REJECTED",
    "STALE",
    "EXPIRED",
    "SUPERSEDED",
)

POLICY_GATE_OUTCOMES = (
    "AUTHORIZED",
    "REJECTED",
    "STALE",
    "BUDGET_DENIED",
    "STAGE_INVALID",
    "LOW_CONFIDENCE",
    "SUPERSEDED",
    "EXPIRED",
)

PROBE_STRATEGIES = (
    "WHY",
    "PROVE",
    "ASSUMPTION_CHALLENGE",
    "COUNTEREXAMPLE",
    "COMPLEXITY",
    "EDGE_CASE",
    "TRADE_OFF",
    "ALTERNATIVE",
    "IMPLEMENTATION_CHOICE",
    "CONSTRAINT_MUTATION",
    "FAILURE_MODE",
    "TRANSFER",
)

PROMPT_ORIGINS = ("STATE_MACHINE", "EXAMINER_DECISION", "SYSTEM")

PROMPT_KINDS = (
    "BASE_QUESTION",
    "CLARIFICATION",
    "PROBE",
    "TRANSITION",
    "INSTRUCTION",
    "TIME_WARNING",
)

PROMPT_STATUSES = (
    "PROPOSED",
    "AUTHORIZED",
    "DELIVERED",
    "ANSWERED",
    "REJECTED",
    "STALE",
    "EXPIRED",
    "INTERRUPTED",
    "CANCELLED",
)

ASSISTANCE_TYPES = (
    "METACOGNITIVE",
    "PROBLEM_NARROWING",
    "CONCEPTUAL_HINT",
    "STRUCTURAL_HINT",
    "DIRECT_TEACHING",
    "DEBUGGING_HINT",
    "CORRECTNESS_FEEDBACK",
)

ASSISTANCE_HINT_LEVELS = (
    "METACOGNITIVE",
    "PROBLEM_NARROWING",
    "CONCEPTUAL_HINT",
    "STRUCTURAL_HINT",
    "DIRECT_TEACHING",
)

ASSISTANCE_TRIGGERS = (
    "CANDIDATE_REQUEST",
    "POST_PROBE_GAP",
    "STUCK_POLICY",
    "DEBUGGING_STALL",
    "CORRECTNESS_REQUEST",
)

RESPONSE_COMPLETION_REASONS = (
    "COMPLETE",
    "INTERRUPTED",
    "SUPERSEDED",
    "TIMEOUT",
    "SPONTANEOUS",
)

RESPONSE_SOURCE_ROLES = (
    "PRIMARY",
    "SUPPORTING",
    "CODE_CONTEXT",
    "RUN_CONTEXT",
)

AI_INVOCATION_STATUSES = (
    "STARTED",
    "SUCCEEDED",
    "FAILED",
    "CANCELLED",
    "TIMED_OUT",
)

CONVERSATION_FLOOR_STATES = (
    "CANDIDATE_SPEAKING",
    "CANDIDATE_THINKING",
    "COUNTERQ_SPEAKING",
    "IDLE",
    "INTERRUPTED",
)

EXECUTION_RUN_STATUSES = (
    "RUNNING",
    "SUCCEEDED",
    "COMPILE_ERROR",
    "RUNTIME_ERROR",
    "TIMED_OUT",
    "OUTPUT_LIMIT_EXCEEDED",
    "PROVIDER_ERROR",
)

TEST_RESULT_STATUSES = ("PASSED", "FAILED", "NOT_RUN")

ASSESSMENT_DIMENSIONS = (
    "CORRECTNESS",
    "DEPTH",
    "INDEPENDENCE",
    "TRANSFER",
    "EXPLANATION_QUALITY",
)

ASSESSMENT_STATUSES = ("PROPOSED", "VALIDATED", "REJECTED", "SUPERSEDED")

EVIDENCE_POLARITIES = ("POSITIVE", "NEGATIVE", "MIXED")

EVIDENCE_STRENGTHS = ("WEAK", "MODERATE", "STRONG")

EVIDENCE_INDEPENDENCE_LEVELS = (
    "INDEPENDENT",
    "AFTER_PROBE",
    "AFTER_LIGHT_GUIDANCE",
    "AFTER_STRONG_HINT",
    "DIRECTLY_TAUGHT",
)

EVIDENCE_VALIDATION_STATUSES = ("VALID", "REJECTED", "INVALIDATED")

EVIDENCE_SOURCE_ROLES = ("PRIMARY", "SUPPORTING", "CONTRADICTING", "CONTEXT")

BREAKPOINT_STATUSES = ("OPEN", "RETEST_PENDING", "IMPROVING", "RESOLVED", "DISMISSED")

BREAKPOINT_EVIDENCE_RELATIONSHIPS = (
    "CREATED",
    "REINFORCED",
    "CONTRADICTED",
    "RESOLUTION_SUPPORT",
)

SKILL_DIMENSION_KEYS = (
    "correctness",
    "explanation_clarity",
    "complexity_reasoning",
    "edge_case_reasoning",
    "trade_off_reasoning",
    "follow_up_adaptability",
    "debugging",
    "constraint_adaptation",
    "thinking_aloud",
    "communication",
)
